### ISSUE TITLE
Overall checklist

### ISSUE THREAD

**Issue by pariahGH** [UTDallasEPICS/Carson-s-Village#35]
- [x] Login
- [x] Invite user (as advocate, as family)
- [x] List pages
- [x] Get page
- [x] Edit page
- [x] List users
- [x] Donation in page
- [x] Donation list by family
- [x] Image Upload
- [x] Add image
- [x] Images associated with page
- [x] Remove image
- [x] Select page profile image
- [x] Page search
- [x] Replace image
- [x] Profile image selection
- [x] Add security to back-end routes
